genericviews/urls.py
from django.urls import path
from . import views

app_name = 'genericviews'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('details/<int:product_id>/', views.ProductDetailView.as_view(), name='details'),
    path('save/', views.saveproducttodb, name='save'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('genericviews.urls')),
    path('', RedirectView.as_view(url='/products/', permanent=True)),
]

genericviews/models.py
from django.db import models


# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

genericviews/forms.py
from django import forms


class ProductForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255, required=True,
                            widget=forms.TextInput(attrs={
                                'class': 'form-control container spacebelow',
                            }))

    description = forms.CharField(label='Description', max_length=255, required=True,
                                  widget=forms.Textarea(attrs={
                                      'class': 'form-control container spacebelow',
                                  }))

genericviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import Product
from .forms import ProductForm


# Create your views here.
class ProductListView(generic.ListView):
    context_object_name = 'product_list'
    template_name = 'genericviews/index.html'

    def get_queryset(self):
        return Product.objects.all()


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'genericviews/details.html'

    def get_object(self):
        return get_object_or_404(Product, id=self.kwargs['product_id'])


def saveproducttodb(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)

        if form.is_valid():
            title = request.POST.get('title', '')
            description = request.POST.get('description', '')

            product = Product(title=title, description=description)
            product.save()

        return redirect('/')

    else:
        form = ProductForm()

    return render(request, 'genericviews/save_product.html', {'form': form})

genericviews/templates/genericviews/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'genericviews/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'genericviews/styles.css' %}" type="text/css">
</head>
<body>
{% block content %}{% endblock %}
<script src="{% static 'genericviews/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'genericviews/js/popper.min.js' %}"></script>
<script src="{% static 'genericviews/js/bootstrap.min.js' %}"></script>
</body>
</html>

genericviews/templates/genericviews/details.html
{% extends 'genericviews/base.html' %}

{% block title %}
CBV App | Product Details
{% endblock %}

{% block content %}
<div class="container">
    <h1>Product Details</h1>
    <hr>
    <h1>{{ product.title }}</h1>
    <h3>{{ product.description }}</h3>
    <hr>
</div>
{% endblock %}

genericviews/templates/genericviews/index.html
{% extends 'genericviews/base.html' %}

{% block title %}
CBV App | Index Page
{% endblock %}

{% block content %}
<div class="container">
    <h1>Product List</h1>
    <hr>
    {% if product_list %}
    <ul>
        {% for product in product_list %}
            <li><a href="{% url 'genericviews:details' product_id=product.id %}">{{ product.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <h3> No product found.</h3>
    <hr>
    {% endif %}
    <br><br><br>
    <hr>
    <a href="{% url 'genericviews:save' %}" class="btn btn-primary">Add Product</a>
</div>
{% endblock %}

genericviews/templates/genericviews/save_product.html
{% extends 'genericviews/base.html' %}

{% block title %}
CBV App | Save Product
{% endblock %}

{% block content %}
<h1>Add/Save Product:</h1>
<form action="{% url 'genericviews:save' %}" method="POST">
    {% csrf_token %}
    <div class="container">
        {{ form }}
        <input type="submit" value="Submit" class="btn btn-primary">
    </div>
</form>
{% endblock %}